services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - db_data:/app/db.sqlite3

  frontend:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  db_data:
